name: MsPAC
channels:
  - hcc
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - avro-python2=1.8.2=py_1
  - bcftools=1.9=h4da6232_0
  - blasr=5.3.2=h82bacf8_5
  - blasr_libcpp=5.3.1=h82bacf8_4
  - htslib=1.9=hc238db4_4
  - libdeflate=1.0=h470a237_0
  - pbbam=0.19.0=h6678c95_1
  - pbcommand=1.1.1=py27_2
  - pbcore=1.6.5=py27_0
  - perl-filesys-df=0.92=pl526h470a237_2
  - pomegranate=0.3.7=py27_2
  - pysam=0.15.1=py27h0380709_0
  - python-consensuscore=1.1.1=py27h02d93b8_2
  - pyvcf=0.6.8=py27_0
  - samtools=1.9=h46bd0b3_0
  - asn1crypto=0.24.0=py27_1003
  - biopython=1.72=py27h470a237_0
  - ca-certificates=2018.11.29=ha4d7672_0
  - cairo=1.14.10=0
  - certifi=2018.11.29=py27_1000
  - cffi=1.11.5=py27h5e8e0c9_1
  - chardet=3.0.4=py27_1003
  - cryptography=2.3.1=py27hdffb7b8_0
  - cryptography-vectors=2.3.1=py27_1000
  - curl=7.63.0=h74213dd_0
  - cython=0.29.1=py27hfc679d8_0
  - dbus=1.13.0=h3a4f0e9_0
  - decorator=4.3.0=py_0
  - enum34=1.1.6=py27_1001
  - expat=2.2.5=hfc679d8_2
  - fontconfig=2.12.6=0
  - freetype=2.8.1=hfa320df_1
  - giflib=5.1.4=h470a237_1
  - glib=2.55.0=h464dc38_2
  - gnuplot=5.2.3=0
  - h5py=2.8.0=py27h097b052_4
  - harfbuzz=1.7.6=0
  - hdf5=1.10.3=hc401514_2
  - icu=58.2=hfc679d8_0
  - idna=2.8=py27_1000
  - ipaddress=1.0.22=py_1
  - iso8601=0.1.12=py_1
  - joblib=0.13.0=py_0
  - jpeg=9c=h470a237_1
  - krb5=1.16.2=hbb41f41_0
  - libcurl=7.63.0=hbdb9355_0
  - libedit=3.1.20170329=0
  - libgd=2.2.5=3
  - libgfortran=3.0.0=1
  - libiconv=1.15=h470a237_3
  - libpng=1.6.34=ha92aebf_2
  - libssh2=1.8.0=h5b517e9_3
  - libtiff=4.0.9=he6b73bb_2
  - libwebp=0.5.2=7
  - libxcb=1.13=h470a237_2
  - libxml2=2.9.8=h422b904_5
  - linecache2=1.0.0=py_1
  - ncurses=5.9=10
  - networkx=2.2=py_1
  - openjdk=11.0.1=h470a237_14
  - openssl=1.0.2p=h470a237_1
  - pango=1.40.14=0
  - pcre=8.41=hfc679d8_3
  - pixman=0.34.0=h470a237_3
  - pthread-stubs=0.4=h470a237_1
  - pycparser=2.19=py_0
  - pyopenssl=18.0.0=py27_1000
  - pysocks=1.6.8=py27_1002
  - pytz=2018.7=py_0
  - readline=7.0=0
  - requests=2.21.0=py27_1000
  - six=1.12.0=py27_1000
  - traceback2=1.4.0=py27_0
  - unittest2=1.1.0=py_0
  - urllib3=1.24.1=py27_1000
  - xorg-libxau=1.0.8=h470a237_6
  - xorg-libxdmcp=1.1.2=h470a237_7
  - blas=1.0=mkl
  - intel-openmp=2019.1=144
  - mkl=2018.0.3=1
  - pip=18.1=py27_0
  - setuptools=40.6.2=py27_0
  - wheel=0.32.3=py27_0
  - pip:
    - kalign=2.0=0
    - zlib=1.2.11=h7b6447c_3
    - bedtools=2.27.1=he941832_2
    - python-consensuscore2=3.1.0=py27_2
    - numpy=1.15.4=py27h1d66e8a_0
    - libgcc-ng=8.2.0=hdf63c60_1
    - qt=5.6.2=h974d657_12
    - perl=5.26.2=h470a237_0
    - mkl_random=1.0.1=py27h4414c95_1
    - python=2.7.15=h33da82c_4
    - bzip2=1.0.6=h14c3975_5
    - numpy-base=1.15.4=py27h81de0dd_0
    - scipy=1.1.0=py27hfa4b5c9_1
    - xz=5.2.4=h14c3975_4
    - graphite2=1.3.12=hfc679d8_1
    - sqlite=3.25.3=h7b6447c_0
    - mkl_fft=1.0.6=py27h7dd41cf_0
    - tk=8.6.8=hbc83047_0
    - gstreamer=1.12.5=h61a6719_0
    - gettext=0.19.8.1=h5e8e0c9_1
    - genomicconsensus=2.3.2=py27_3
    - canu=1.8=pl526h470a237_0
    - libgcc=7.2.0=h69d50b8_2
    - libffi=3.2.1=hd88cf55_4
    - libgfortran-ng=7.3.0=hdf63c60_0
    - gst-plugins-base=1.12.5=hde13a9d_0
    - libstdcxx-ng=8.2.0=hdf63c60_1
